"use client";
import { useState } from 'react';
import Navbar from "@/components/Navbar";
import { Film, ShieldCheck, AlertTriangle, ChevronRight } from 'lucide-react';
import { generateAiClipPlan, AiClipPlan } from '@/lib/media/aiClipPlanner';

const defaultTopics = [
  'Fortnite item shop today',
  'Best XP maps this week',
  'What pros are using',
  'Fortnite update breakdown',
  'Best beginner settings'
];

export default function AiClipsPage() {
  const [selectedPlan, setSelectedPlan] = useState<AiClipPlan | null>(null);
  const [activeTopic, setActiveTopic] = useState('');

  const handleSelect = (topic: string) => {
    setActiveTopic(topic);
    setSelectedPlan(generateAiClipPlan(topic));
  };

  return (
    <>
      <Navbar />
      <div className="container mx-auto px-4 py-16 max-w-6xl space-y-12">
        
        <div>
          <h1 className="text-4xl font-heading font-black uppercase mb-4 flex items-center gap-3">
            <Film className="w-10 h-10 text-purple-400" /> AI Clip Plans
          </h1>
          <p className="text-white/60 max-w-2xl">
            Original video scripts, storyboards, and thumbnail concepts generated by FortHub. These are planning tools — no copyrighted footage is used.
          </p>
        </div>

        {/* Safety Banner */}
        <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-xl p-6 flex items-start gap-4">
          <AlertTriangle className="w-6 h-6 text-yellow-400 shrink-0 mt-1" />
          <div>
            <h3 className="font-bold text-yellow-400 mb-1">AI Content Rules</h3>
            <ul className="text-sm text-yellow-400/80 space-y-1 list-disc list-inside">
              <li>No copyrighted Fortnite gameplay footage</li>
              <li>No creator footage without permission</li>
              <li>No official Epic trailers unless officially embedded</li>
              <li>Scripts and visuals must be original or royalty-free</li>
            </ul>
          </div>
        </div>

        {/* Topic Selector */}
        <div>
          <h2 className="text-xl font-bold uppercase tracking-widest text-white mb-4">Select a Topic</h2>
          <div className="flex flex-wrap gap-3">
            {defaultTopics.map(topic => (
              <button
                key={topic}
                onClick={() => handleSelect(topic)}
                className={`px-4 py-2 rounded-lg text-sm font-bold uppercase tracking-wider border transition-all ${
                  activeTopic === topic
                    ? 'bg-primary/20 text-primary border-primary/30'
                    : 'bg-white/5 text-white/60 border-white/10 hover:bg-white/10 hover:text-white'
                }`}
              >
                {topic}
              </button>
            ))}
          </div>
        </div>

        {/* Selected Plan */}
        {selectedPlan && (
          <div className="space-y-8">
            <div className="bg-[#12131c] border border-primary/20 rounded-xl p-8 space-y-6">
              <h2 className="text-2xl font-black text-white">{selectedPlan.title}</h2>
              
              <div>
                <h3 className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-2">Hook</h3>
                <p className="text-primary font-bold text-lg">{selectedPlan.hook}</p>
              </div>

              <div>
                <h3 className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-2">Script</h3>
                <p className="text-white/80 text-sm leading-relaxed whitespace-pre-line bg-white/5 p-4 rounded-lg">{selectedPlan.script}</p>
              </div>

              <div>
                <h3 className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-2">Scene List</h3>
                <ul className="space-y-2">
                  {selectedPlan.sceneList.map((scene, i) => (
                    <li key={i} className="text-sm text-white/70 flex items-start gap-2">
                      <ChevronRight className="w-4 h-4 text-primary shrink-0 mt-0.5" /> {scene}
                    </li>
                  ))}
                </ul>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h3 className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-2">Thumbnail Prompt</h3>
                  <p className="text-sm text-white/70 bg-white/5 p-3 rounded">{selectedPlan.thumbnailPrompt}</p>
                </div>
                <div>
                  <h3 className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-2">Caption</h3>
                  <p className="text-sm text-white/70 bg-white/5 p-3 rounded">{selectedPlan.caption}</p>
                </div>
              </div>

              <div>
                <h3 className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-2">Hashtags</h3>
                <div className="flex flex-wrap gap-2">
                  {selectedPlan.hashtags.map(tag => (
                    <span key={tag} className="text-xs bg-blue-500/20 text-blue-400 px-2 py-1 rounded">{tag}</span>
                  ))}
                </div>
              </div>
            </div>

            {/* Legal Checklist */}
            <div className="bg-green-500/10 border border-green-500/20 rounded-xl p-6">
              <h3 className="font-bold text-green-400 mb-4 flex items-center gap-2">
                <ShieldCheck className="w-5 h-5" /> Legal & Safety Checklist
              </h3>
              <ul className="space-y-2">
                {selectedPlan.legalChecklist.map((item, i) => (
                  <li key={i} className="text-sm text-green-400/80 flex items-center gap-2">
                    <span className="w-4 h-4 border border-green-500/30 rounded flex-shrink-0" /> {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

      </div>
    </>
  );
}
